Test: tf plan 명령어 변경

diff --git a/.github/workflows/dev-plan.yml b/.github/workflows/dev-plan.yml
--- a/.github/workflows/dev-plan.yml
+++ b/.github/workflows/dev-plan.yml
@@ -47,15 +47,16 @@ jobs:
         id: tf-plan
         working-directory: ${{ env.WORK_DIR }}
         run: |
-          export exitcode=0
-          terraform plan -input=false -var-file="environment/dev/dev.tfvars" -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+          terraform plan -input=false -var-file="environment/dev/dev.tfvars" -out tfplan
+          # export exitcode=0
+          # terraform plan -input=false -var-file="environment/dev/dev.tfvars" -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          # echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
+          # if [ $exitcode -eq 1 ]; then
+          #   echo Terraform Plan Failed!
+          #   exit 1
+          # else 
+          #   exit 0
+          # fi
         
